spring:
  application:
    name: payment-initiator-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:./payments;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #driverClassName: org.h2.Driver
    #username: sa
    #password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8080

logging:
  level:
    com.demopipeline.payments: DEBUG           # Your payment classes
    com.demopipeline.payments.initiator: DEBUG # PaymentService/Controller
    org.springframework.jms: DEBUG             # JmsTemplate/ActiveMQ
    org.springframework.web: DEBUG             # Controller mappings
    root: INFO
